# Generated by Django 4.1.7 on 2023-03-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='name1',
            new_name='name',
        ),
    ]
