# Generated by Django 4.1.7 on 2023-03-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_desc1_name_desc_rename_img1_name_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='img',
            new_name='img11',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='name1',
        ),
    ]
