# Generated by Django 4.1.7 on 2023-03-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_img_name_img11_rename_name_name_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='img11',
            new_name='img1',
        ),
    ]
